language: php

php:
  - 5.3.2
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --no-interaction --dev

script: "./libs/bin/tester tests/ && ./libs/bin/tester demo/tests/"
